- name: Deploy the web application
  hosts: webanddb
  become: true
  tasks:
    - name: Install all the required dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python 
        - python-setuptools 
        - python-dev 
        - build-essential 
        - python-pip 
        - python-mysqldb
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
