- name: Deploy the web application
  hosts: web&db1,web&db2
  become: true
  tasks:
    - name: Install all the required dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python 
        - python-setuptools 
        - python-dev 
        - build-essential 
        - python-pip 
        - python-mysqldb

    - name: Install the Mysql Datanase
      apt: name={{ item }} state=installed
      with_items:
        - mysql-server 
        - mysql-client
    
    - name: start the Mysql server
      service: 
          name: mysql 
          state: started
          enabled: yes

    - name: configure the mysql database
      mysql_db: name=employee_db state=present

    - name: create the root user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: install the python dependencies
      pip: name= "{{ item }}" state=present
      with_items:
        - flask
        - flask-mysql
    
    - name: copy the code
      copy: src=app.py dest=/opt/app.py

    - name: start the web server
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
